[package]
name = "telefeed"
version = "0.5.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2021"

[dependencies]
atom_syndication = "0.12.2"
base64 = "0.21.5"
bytes = "1.5.0"
chrono = "0.4.31"
dotenvy = "0.15.7"
env_logger = "0.10.1"
log = "0.4.20"
redis = { version = "0.23.3", features = ["tokio-comp"] }
reqwest = "0.11.22"
rss = "2.0.6"
serde = "1.0.193"
serde_yaml = "0.9.27"
tgbot = "0.19.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
