[package]
name = "telefeed"
version = "0.2.3"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2018"

[dependencies]
atom_syndication = "0.7.0"
base64 = "0.11.0"
bytes = "0.5.4"
chrono = "0.4.7"
darkredis = "0.6.1"
dotenv = "0.15.0"
env_logger = "0.7.1"
log = "0.4.8"
reqwest = "0.10.1"
rss = "1.8.0"
serde = "1.0.104"
serde_yaml = "0.8.11"
tgbot = "0.7.0"
tokio = { version = "0.2.9", default-features = false, features = ["fs", "macros", "sync", "time"] }
