[package]
name = "telefeed"
version = "0.4.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]
edition = "2021"

[dependencies]
atom_syndication = "0.11.0"
base64 = "0.13.0"
bytes = "1.1.0"
chrono = "0.4.19"
darkredis = "0.8.0"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
reqwest = "0.11.9"
rss = "2.0.0"
serde = "1.0.136"
serde_yaml = "0.8.23"
tgbot = "0.17.0"
tokio = "1.16.1"
